version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
  # Python
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
  # Node.js
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
